### ISSUE TITLE
Problems with full res images that cross the Prime Meridian

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#139] opened 2017-09-06 15:19 UTC
From Liam Gumley:

Dear CSPP P2G gurus,

I am reprojecting MODIS images which span the prime meridian. I notice that artifacts (black pixels) are present along the prime meridian in the reprojected images where 250 meter resolution bands are used (e.g., vis02 and true_color products).

Here is my P2G v2.1 test case (run on bolt.ssec.wisc.edu):

export POLAR2GRID_HOME=$DBVM_HOME/apps/polar2grid/polar2grid
source $POLAR2GRID_HOME/bin/polar2grid_env.sh
modis2gtiff.sh -p vis02 bt31 -f level1
crefl2gtiff.sh -f level1

The MODIS input files, and the resulting images are available here:

ftp://ftp.ssec.wisc.edu/pub/gumley/p2g_prime_meridian

An example of the artifacts is shown in the attached image, clipped from the true color image in the test case above. If you examine the same region in the Band 31 image, no artifacts are seen.

Regards,
Liam.
<img width="1091" alt="pastedgraphic-1" src="https://user-images.githubusercontent.com/1848019/30119869-c99a598e-92ec-11e7-9cf7-ca746a60467c.png">
<img width="969" alt="pastedgraphic-2" src="https://user-images.githubusercontent.com/1848019/30119878-d0f8cc10-92ec-11e7-8960-8d09ad6d7ae4.png">

**Comment by davidh-ssec** [comment] 2017-09-06 16:39
From what I can tell this is caused by the EWA resampling. Still debugging.

Resample vis02 1km version with EWA: No line
Resample vis02 500m version with EWA: Line
Resample vis02 250m version with EWA: Line
Resample vis02 500m version wth nearest neighbor: No line

**Comment by davidh-ssec** [comment] 2017-09-18 22:16
This turned out to be due to 32-bit float versus 64-bit float precision in the interpolation/extrapolation process for the MODIS 250m and 500m navigation creation. With 32-bit floats the math resulted in 4-12 pixels at the prime meridian all resolving to 0 when converted from euclidian X/Y/Z space to Longitude/Latitude space. By changing the data type of the coordinates involved to 64-bit this removed these 0 points and produced the expected image. This will be fixed in the 2.2.0 release of Polar2Grid and is currently in the develop branch of the repository.

**Closed by davidh-ssec** 2017-09-18 22:16 UTC
