### ISSUE TITLE
Terra reprojection fails with missing data at start of pass

### ISSUE THREAD

**Issue by kathys** [davidh-ssec/polar2grid#124] opened 2016-12-15 15:41 UTC
Here is a bug report from Liam:

Kathy,

I have a Terra MODIS 1KM dataset from a DB site in far eastern Russia which has a little bit of missing data in the first couple of scans. P2G v2.0 cannot use the ‘lcc_asia’ grid to create an image from it because the computed value of ‘origin_y' for the granule is 1e+30. I downloaded a Terra MODIS granule from LAADS for about the same date/time and it works fine with the lcc_asia grid. My theory is that P2G is using a bad lat/lon value when it tries to compute ‘origin_y’.

I have created a self-contained test case in this tarfile:
ftp://ftp.ssec.wisc.edu/pub/incoming/p2g_test.tar.gz

To run the test case:

wget ftp://ftp.ssec.wisc.edu/pub/incoming/p2g_test.tar.gz
tar -zxvf p2g_test.tar.gz               # creates a directory named p2g_test
cd p2g_test
./p2g_test.bash

The test script downloads and installs P2G v2.0. It then uses the LAADS dataset to create BT31 images for the wgs84_fit and lcc_asia projections. Then it tries to do the same for the DB data in the ‘input’ directory. It will create an image for the wgs84_fit grid, but it will fail for the DB data in the ‘input’ directory because it says 0.0% of the grid is filled. If you look at the log file, you will see

[2016-12-15 15:27:23,082] : PID  28908 : DEBUG    : polar2grid.remap.remap : run_ll2cr : Grid information:
	grid_name: lcc_asia
	proj4_definition: +proj=lcc +datum=WGS84 +ellps=WGS84 +lat_0=25 +lat_1=25 +lon_0=105 +units=m +no_defs
	cell_width: 1000.0
	cell_height: -1000.0
	width: 0
	height: 0
	origin_x: -296156.139747
	origin_y: 1e+30
[2016-12-15 15:27:23,082] : PID  28908 : DEBUG    : polar2grid.remap.remap : _safe_remove : Removing intermediate file 'll2cr_rows_lcc_asia_1000m_nav.dat'...
[2016-12-15 15:27:23,082] : PID  28908 : DEBUG    : polar2grid.remap.remap : _safe_remove : Removing intermediate file 'll2cr_cols_lcc_asia_1000m_nav.dat'...
[2016-12-15 15:27:23,082] : PID  28908 : ERROR    : polar2grid.remap.remap : run_ll2cr : Data does not fit in grid lcc_asia because it only 0.000000% of the swath is used
[2016-12-15 15:27:23,082] : PID  28908 : ERROR    : polar2grid.remap.remap : remap_scene : Remapping error
[2016-12-15 15:27:23,082] : PID  28908 : DEBUG    : modis2gtiff : main : Remapping data exception: 
Traceback (most recent call last):
  File "/home/gumley/p2g_test/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid-2.0.0-py2.7-linux-x86_64.egg/polar2grid/glue.py", line 338, in main
    gridded_scene = remapper.remap_scene(scene, grid_name, **remap_kwargs)
  File "/home/gumley/p2g_test/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid-2.0.0-py2.7-linux-x86_64.egg/polar2grid/remap/remap.py", line 162, in remap_scene
    self.run_ll2cr(best_swath_def, grid_def, swath_usage=kwargs.get("swath_usage", SWATH_USAGE))
  File "/home/gumley/p2g_test/polar2grid_v_2_0/ShellB3/lib/python2.7/site-packages/polar2grid-2.0.0-py2.7-linux-x86_64.egg/polar2grid/remap/remap.py", line 220, in run_ll2cr
    raise RuntimeError("Data does not fit in grid %s" % (grid_name,))
RuntimeError: Data does not fit in grid lcc_asia
[2016-12-15 15:27:23,082] : PID  28908 : ERROR    : modis2gtiff : main : Remapping data failed

**Comment by davidh-ssec** [comment] 2016-12-15 15:51
This should be fixed in this commit 3347adf68c0455b93397e4db1557bf3e53209045.

The problem is that this commit came 14 days after the last version 2.0 commit. I will do some tests with the current development version of version 2.1 to make sure this works.

**Comment by davidh-ssec** [comment] 2016-12-15 17:58
I just ran the equivalent of the following commands with my development installation using the latest code that will become version 2.1:

    modis2gtiff.sh -v -p bt31 -f ../input/t1.16348.0309.*.hdf -g lcc_asia

And the geotiff was properly created and looks good. I think that proves that the above commit fixes what it was meant to fix. If we are still worried about this we can take the latest v2.1rc tarball and test it against this data.

**Closed by davidh-ssec** 2016-12-15 17:58 UTC
Labels: bug
